services:
  ical-filter-proxy:
    build:
      context: .
    container_name: ical-filter-proxy
    command: --debug
    ports:
      - "8027:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./certs:/app/certs
      - ./data:/data
    restart: unless-stopped
